import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import "beercss";
import "material-dynamic-colors";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"min-h-screen " + inter.className}>
        <div className="flex flex-col items-center justify-between container m-auto pt-10">
          <nav className="w-full items-center justify-between flex">
            <h1 className="font-mono">adenlall</h1>
            <div>
              <a target="_blank" href="https://www.linkedin.com/in/janahbilal/">
                <button className="border">linkedin</button>
              </a>
              <a target="_blank" href="https://github.com/adenlall">
                <button>github</button>
              </a>
            </div>
          </nav>
        </div>
        {children}
      </body>
    </html>
  );
}
